// Code generated by MockGen. DO NOT EDIT.
// Source: clients/http/interface.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	http "github.com/conduitio/conduit-connector-stripe/clients/http"
	gomock "github.com/golang/mock/gomock"
)

// MockHTTP is a mock of HTTP interface.
type MockHTTP struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPMockRecorder
}

// MockHTTPMockRecorder is the mock recorder for MockHTTP.
type MockHTTPMockRecorder struct {
	mock *MockHTTP
}

// NewMockHTTP creates a new mock instance.
func NewMockHTTP(ctrl *gomock.Controller) *MockHTTP {
	mock := &MockHTTP{ctrl: ctrl}
	mock.recorder = &MockHTTPMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTP) EXPECT() *MockHTTPMockRecorder {
	return m.recorder
}

// GetResources mocks base method.
func (m *MockHTTP) GetResources(startingAfter string) (http.StripeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResources", startingAfter)
	ret0, _ := ret[0].(http.StripeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResources indicates an expected call of GetResources.
func (mr *MockHTTPMockRecorder) GetResources(startingAfter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResources", reflect.TypeOf((*MockHTTP)(nil).GetResources), startingAfter)
}
