// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package config

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigBatchSize    = "batchSize"
	ConfigResourceName = "resourceName"
	ConfigSecretKey    = "secretKey"
	ConfigSnapshot     = "snapshot"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigBatchSize: {
			Default:     "10",
			Description: "BatchSize is the configuration name for the number of objects in the batch returned from Stripe.",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{
				config.ValidationGreaterThan{V: 0},
				config.ValidationLessThan{V: 100001},
			},
		},
		ConfigResourceName: {
			Default:     "",
			Description: "ResourceName is the configuration name for Stripe resource.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigSecretKey: {
			Default:     "",
			Description: "SecretKey is the configuration name for Stripe secret key.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigSnapshot: {
			Default:     "true",
			Description: "Snapshot is the configuration name for the Snapshot field.",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{},
		},
	}
}
